# Generated by Django 3.1.1 on 2020-09-30 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('1', 'Новости недвижимости'), ('2', 'Жилая недвижимость'), ('3', 'Коммерческая недвижимость'), ('4', 'Загородная недвижимость'), ('5', 'Зарубежная недвижимость'), ('6', 'Новостройки'), ('7', 'Вторичное жилье'), ('8', 'Строительство'), ('9', 'Ремонт квартир'), ('10', 'Отделка помещений'), ('11', 'Строительные материалы'), ('12', 'Дизайн квартир'), ('13', 'Проектирование помещений'), ('14', 'Инвестиции в недвижимость'), ('15', 'Законодательство о недвижимости'), ('16', 'Ипотека'), ('17', 'Реновация')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPostRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('reacted_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.posting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='who_liked',
            field=models.ManyToManyField(related_name='liked', through='posts.UserPostRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
