# Generated by Django 3.1.1 on 2020-10-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201001_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='paid_content',
            field=models.BooleanField(default=False),
        ),
    ]
