# Generated by Django 3.1.1 on 2020-10-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posting_paid_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='slug',
        ),
    ]
