# Generated by Django 3.1.1 on 2020-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_posting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
