# Generated by Django 3.1.1 on 2020-10-02 19:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_posting_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='category',
        ),
        migrations.AddField(
            model_name='posting',
            name='choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Новости недвижимости'), ('2', 'Жилая недвижимость'), ('3', 'Коммерческая недвижимость'), ('4', 'Загородная недвижимость'), ('5', 'Зарубежная недвижимость'), ('6', 'Новостройки'), ('7', 'Вторичное жилье'), ('8', 'Строительство'), ('9', 'Ремонт квартир'), ('10', 'Отделка помещений'), ('11', 'Строительные материалы'), ('12', 'Дизайн квартир'), ('13', 'Проектирование помещений'), ('14', 'Инвестиции в недвижимость'), ('15', 'Законодательство о недвижимости'), ('16', 'Ипотека'), ('17', 'Реновация')], default='Новости недвижимости', max_length=50),
            preserve_default=False,
        ),
    ]
