# Generated by Django 3.1.1 on 2020-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201002_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='images',
            field=models.FileField(blank=True, upload_to='post_image/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
