# Generated by Django 3.1.1 on 2020-10-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201003_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='images',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to='post_image/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posting')),
            ],
        ),
    ]
