# Generated by Django 3.1.1 on 2020-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_posting_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='images',
            field=models.ImageField(blank=True, upload_to='posting_images/'),
        ),
    ]
