# Generated by Django 3.1.1 on 2020-10-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_posting_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='images',
        ),
    ]
