# Generated by Django 3.1.1 on 2020-10-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
