# Generated by Django 3.1.1 on 2020-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201002_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, default='image.png', upload_to='profile_img/'),
            preserve_default=False,
        ),
    ]
