# Generated by Django 3.1.1 on 2020-10-02 16:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_fields', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Новости недвижимости'), ('2', 'Жилая недвижимость'), ('3', 'Коммерческая недвижимость'), ('4', 'Загородная недвижимость'), ('5', 'Зарубежная недвижимость'), ('6', 'Новостройки'), ('7', 'Вторичное жилье'), ('8', 'Строительство'), ('9', 'Ремонт квартир'), ('10', 'Отделка помещений'), ('11', 'Строительные материалы'), ('12', 'Дизайн квартир'), ('13', 'Проектирование помещений'), ('14', 'Инвестиции в недвижимость'), ('15', 'Законодательство о недвижимости'), ('16', 'Ипотека'), ('17', 'Реновация')], max_length=17)),
            ],
        ),
    ]
