# Generated by Django 3.1.1 on 2020-10-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='my_fields',
        ),
    ]
