# Generated by Django 3.1.1 on 2020-10-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_auto_20201003_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
